#brightease:
#  filePath: /opt/root/carsfile/
#  tempUpLoadPath: /opt/root/carsfile/temp/
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.0.110:3306/sanatorium?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    druid:
#      initial-size: 5 #连接池初始化大小
#      min-idle: 10 #最小空闲连接数
#      max-active: 20 #最大连接数
#      web-stat-filter:
#        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#      stat-view-servlet: #访问监控网页的登录用户名和密码
#        login-username: druid
#        login-password: druid
#  redis:
#    database: 0
#    host: 192.168.29.102
#    port: 6379
#    password: 123456     # 密码（默认为空）
#    timeout: 6000  # 连接超时时长（timeout*60*60）
#    jedis:
#      pool:
#        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 10      # 连接池中的最大空闲连接
#        min-idle: 5       # 连接池中的最小空闲连接
#ftp:
#  host: 192.168.29.102
#  port: 22
#  username: root
#  password: 123456
#  defatultport: 22
#  serverpath: bju
#  req:
#    url: 192.168.29.102
##server:
##  tomcat:
##    max-http-post-size: -1
#
